export const loadingPhrases = [
  "Preparando tu experiencia de compra...",
  "Cargando los mejores productos para ti...",
  "Estamos organizando todo para ti...",
  "Buscando las mejores ofertas del momento...",
  "Actualizando el catálogo de productos...",
  "Configurando tu tienda personalizada...",
  "Optimizando tu navegación...",
  "Verificando disponibilidad de productos...",
  "Preparando recomendaciones especiales...",
  "Cargando novedades y promociones...",
  "Conectando con los mejores proveedores...",
  "Organizando categorías para ti...",
  "Sincronizando tu carrito de compras...",
  "Ajustando precios y descuentos...",
  "Cargando información de envíos...",
  "Preparando detalles de productos...",
  "Verificando stock disponible...",
  "Configurando métodos de pago...",
  "Casi listo para mostrarte todo...",
  "Un momento, estamos terminando...",
  "Personalizando tu experiencia...",
  "Cargando tus favoritos...",
  "Preparando ofertas exclusivas...",
  "Actualizando imágenes de productos...",
  "Verificando la mejor ruta de entrega...",
];
