export const testimonials = [
  {
    imgSrc: "/images/avatar/review-1.jpg",
    name: "Sofía Martínez",
    color: "Negro",
    verified: true,
    rating: 5,
    text: `Excelente servicio, el paquete llegó en perfectas condiciones y mucho más rápido de lo que esperaba. La comunicación durante todo el proceso fue muy clara. Definitivamente volvería a usar Shipazo para mis próximas importaciones.`,
    date: "12 de enero de 2025 a las 10:35",
  },
  {
    imgSrc: "/images/avatar/review-3.jpg",
    name: "Carlos Mendoza",
    color: "Azul",
    verified: true,
    rating: 5,
    text: `Llevaba tiempo buscando un servicio confiable para traer productos desde Estados Unidos y por fin lo encontré. El proceso es muy sencillo, los precios son transparentes y el equipo siempre resolvió mis dudas. Lo recomiendo ampliamente.`,
    date: "28 de enero de 2025 a las 14:52",
  },
  {
    imgSrc: "/images/avatar/review-5.jpg",
    name: "Andrea López",
    color: "Blanco",
    verified: true,
    rating: 4,
    text: `Muy buena experiencia en general. Traje varios artículos electrónicos y llegaron todos sin ningún problema. Solo sugeriría mejorar un poco los tiempos de actualización del tracking, pero en cuanto a seguridad y precio, están muy bien.`,
    date: "5 de febrero de 2025 a las 09:18",
  },
];

export const testimonials2 = [
  {
    wowDelay: "",
    imgSrc: "/images/avatar/review-2.jpg",
    name: "Roberto Fuentes",
    color: "Gris",
    verified: true,
    stars: 5,
    text: `Increíble experiencia desde el primer pedido. El sistema de casillero es muy fácil de usar y los costos de envío son mucho más bajos comparados con otras opciones que había probado antes. ¡Ya hice mi tercer pedido!`,
    date: "3 de enero de 2025 a las 16:40",
  },
  {
    wowDelay: "0.1s",
    imgSrc: "/images/avatar/review-4.jpg",
    name: "Gabriela Torres",
    color: "Rosa",
    verified: true,
    stars: 5,
    text: `Traje ropa y accesorios de varias tiendas americanas y todo llegó perfecto. El empaque es muy cuidadoso y el tiempo de entrega fue de menos de una semana. Estoy muy contenta con el servicio, superó mis expectativas.`,
    date: "19 de enero de 2025 a las 11:05",
  },
  {
    wowDelay: "0.2s",
    imgSrc: "/images/avatar/review-6.jpg",
    name: "Diego Herrera",
    color: "Negro",
    verified: true,
    stars: 5,
    text: `Al principio tenía dudas sobre importar por primera vez, pero el equipo de Shipazo me guió en cada paso. Los precios son justos y el servicio al cliente es excelente. Mi paquete llegó antes de lo prometido y en perfecto estado.`,
    date: "7 de febrero de 2025 a las 08:30",
  },
  {
    wowDelay: "",
    imgSrc: "/images/avatar/review-1.jpg",
    name: "María José Castillo",
    color: "Blanco",
    verified: true,
    stars: 4,
    text: `Muy satisfecha con el servicio. Ya llevo varios meses usando Shipazo para mis compras online y siempre ha sido una experiencia positiva. Los precios son competitivos y el proceso de consolidación de paquetes me ha ahorrado mucho dinero.`,
    date: "14 de febrero de 2025 a las 13:22",
  },
];
